# -*- coding: utf-8 -*-
"""
Created on Thu Jun 27 20:42:42 2019

@author: Pale
"""

name=["MOHAMED MOHAMED ALI",
"MUDIMU JOSHUA",
"MUHUMED MOHAMEDNOOR AHMED",
"ALHASAN MOHAMMAD AMIN IBRAHIM",
"GYASI GIDEON",
"MAZIKU OCTAVIAN JONATHAN CHARLES EDWARD",
"MUPFUKIREI LEAVEN ROMEO",
"CHITONJE EVANS TINOTENDA",
"AL-HARAZI NAWAF ABBAS AHMED",
"SAYED MOHSEN ADNAN ALAWI SALMAN ALHALAI",
"BOBSEET ABDULRAHMAN SAEED IBRAHIM"]

fo=open("p1.txt","w")
for x in name:
    fo.write(x+"\n")
    
fo.close()
print("Goodbye")